version: '2'
services:
  phpldapadmin:
    image: osixia/phpldapadmin
    volumes:
      - /etc/ssl/ldap.liukersun.com/:/container/service/phpldapadmin/assets/apache2/certs
    environment:
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: cert.pem
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: key.pem
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: fullchain.pem
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    links:
      - openldap
    ports:
      - 6443:443
    restart: always
  openldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "liukersun.com"
      LDAP_DOMAIN: liukersun.com
      LDAP_ADMIN_PASSWORD: eX4mP13p455w0Rd
    volumes:
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    restart: always
    ports:
      - 389:389
      - 689:689
