# docker-compose.yml

version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: eX4mP13p455w0Rd
    restart: always
  keycloak:
    image: bitnami/keycloak:12.0.4
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: eX4mP13p455w0Rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: eX4mP13p455w0Rd
      PROXY_ADDRESS_FORWARDING: true
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
